In [60]:
import numpy as np

## datatypes and attributes

In [2]:
#numpy main datatype is ndarray 
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [3]:
a2 = np.array([
    [1,2,3,],
    [4,5,6,],
    [7,8,9]
])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a3 = np.array([[[1,2,3,],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(3, 3)

In [18]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim

1

In [15]:
a2.ndim

2

In [19]:
a3.ndim

3

In [24]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [25]:
a1.size ,a2.size , a3.size

(3, 9, 18)

In [26]:
type(a1)

numpy.ndarray

In [61]:
# create a data frame from NumPy array
import pandas as pd

df =pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

###  2. creating arrays

In [3]:
sample_arrays = np.array([1,2,3])
sample_arrays

array([1, 2, 3])

In [4]:
sample_arrays.dtype

dtype('int32')

In [7]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
type(ones)

numpy.ndarray

In [9]:
zeros = np.zeros((2,3))

In [10]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
range_array =np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [43]:
random_aray= np.random.randint(0,10,size=(3,5))
random_aray

array([[2, 6, 2, 5, 0],
       [7, 6, 7, 2, 4],
       [2, 9, 3, 7, 3]])

In [17]:
random_aray_2=np.random.random((5,3))
random_aray_2

array([[0.77023253, 0.9885958 , 0.55241429],
       [0.26001415, 0.4147205 , 0.34490959],
       [0.06925435, 0.53301974, 0.24895775],
       [0.01265067, 0.19662611, 0.06139259],
       [0.77623805, 0.45974025, 0.09857546]])

In [18]:
random_aray_3 = np.random.rand(5,3)
random_aray_3

array([[0.07049603, 0.70119392, 0.71030606],
       [0.52566986, 0.43098956, 0.3057075 ],
       [0.40630135, 0.51896097, 0.50863327],
       [0.18677721, 0.14098013, 0.34441974],
       [0.80660625, 0.0983101 , 0.90487489]])

In [33]:
#Pseudo-random-numbers
np.random.seed(seed=99999)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## manipulating and comparison

##### arithmetic

In [4]:
a1


array([1, 2, 3])

In [8]:
ones =np.ones(3)

In [6]:
ones

array([1., 1., 1.])

In [7]:
a1 + ones

array([2., 3., 4.])

In [8]:
a1 - ones

array([0., 1., 2.])

In [9]:
a1 * ones

array([1., 2., 3.])

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [6]:
a2 * a3

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]]])

In [9]:
a1 / ones

array([1., 2., 3.])

In [10]:
a1 // ones

array([1., 2., 3.])

In [11]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [12]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [13]:
np.add(a1,ones)

array([2., 3., 4.])

In [14]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [15]:
a2 % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [16]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [17]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### aggregation

In [18]:
listy_list = [1,2,3]
type(listy_list)

list

In [19]:
sum(listy_list)

6

In [20]:
sum(a1)

6

In [22]:
# create a massive array 
massive_array =np.random.random(100000)
massive_array

array([0.24766854, 0.96878553, 0.06331281, ..., 0.25656486, 0.44388369,
       0.364464  ])

In [24]:
massive_array[:10]

array([0.24766854, 0.96878553, 0.06331281, 0.24246506, 0.97941781,
       0.66344525, 0.24010629, 0.06284258, 0.47237578, 0.05148236])

In [26]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

20 ms ± 387 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
106 µs ± 2.84 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [27]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.mean(a2)

5.0

In [29]:
np.max(a2)

9

In [30]:
np.min(a2)

1

In [31]:
np.std(a2)

2.581988897471611

In [32]:
np.var(a2)

6.666666666666667

### Comparison opertator 

In [33]:
a1


array([1, 2, 3])

In [34]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a1 > a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [36]:
a1 < a2

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [38]:
 a1 == a1

array([ True,  True,  True])

In [39]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

## sorting array

In [48]:
random_aray

array([[2, 6, 2, 5, 0],
       [7, 6, 7, 2, 4],
       [2, 9, 3, 7, 3]])

In [45]:
np.sort(random_aray)

array([[0, 2, 2, 5, 6],
       [2, 4, 6, 7, 7],
       [2, 3, 3, 7, 9]])

In [49]:
np.argsort(random_aray)

array([[4, 0, 2, 3, 1],
       [3, 4, 1, 0, 2],
       [0, 2, 4, 3, 1]], dtype=int64)

In [47]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [50]:
np.argmax(a1)

2

In [52]:
np.argmax(random_aray,axis=0)

array([1, 2, 1, 2, 1], dtype=int64)

In [53]:
np.argmax(random_aray,axis=1)

array([1, 0, 1], dtype=int64)

## practical Example - NumPy in Action 

In [68]:
< img src="images\panda.png" />

SyntaxError: invalid syntax (2321857514.py, line 1)

In [65]:
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [67]:
panda.size, panda.shape , panda.ndim

(24465000, (2330, 3500, 3), 3)

In [69]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [71]:
<img src="images/car-photo.png" />

SyntaxError: invalid syntax (3654034618.py, line 1)

In [72]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [73]:
car[:5]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [74]:
dog = imread("images/dog-photo.png")
print(type(dog))
dog[:5]

<class 'numpy.ndarray'>


array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274