## introduction to sci kit learn 

In [1]:
%matplotlib inline 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## An end to end Scikit learn workflow

In [2]:
# get the data ready 
heart_dieseas = pd.read_csv("heart-disease.csv")
heart_dieseas.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
#feature matrix 
x = heart_dieseas.drop("target",axis=1)

#label
y= heart_dieseas["target"]

In [4]:
# choose the right model and hyperparameter 
from sklearn.ensemble import RandomForestClassifier
clf= RandomForestClassifier()

#default hyperparameter
clf.get_params()


{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [2]:
#fit the model to the training data 
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=0.2)

NameError: name 'x' is not defined

In [14]:
clf.fit(xtrain,ytrain);

In [15]:
#make a prediction
y_label=clf.predict(np.array([0,2,3,4]))

C:\Users\yuvar\OneDrive\Desktop\ML\ML1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [16]:
y_pred=clf.predict(xtest)
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [18]:
ytest

110    1
232    0
155    1
159    1
251    0
      ..
156    1
122    1
74     1
180    0
301    0
Name: target, Length: 61, dtype: int64

In [19]:
#4 evalute the model
clf.score(xtrain,ytrain)

1.0

In [21]:
clf.score(xtest,ytest)

0.819672131147541

In [22]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.71      0.76        24
           1       0.82      0.89      0.86        37

    accuracy                           0.82        61
   macro avg       0.82      0.80      0.81        61
weighted avg       0.82      0.82      0.82        61



In [23]:
confusion_matrix(ytest,y_pred)

array([[17,  7],
       [ 4, 33]], dtype=int64)

In [24]:
accuracy_score(ytest,y_pred)

0.819672131147541

In [29]:
#improve the model
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimator....")
    clf=RandomForestClassifier(n_estimators=i).fit(xtrain,ytrain)
    print(f"Model accuracy  on test set :{clf.score(xtest,ytest)*100:.2f} \n")

Trying model with 10 estimator....
Model accuracy  on test set :77.05 

Trying model with 20 estimator....
Model accuracy  on test set :78.69 

Trying model with 30 estimator....
Model accuracy  on test set :80.33 

Trying model with 40 estimator....
Model accuracy  on test set :83.61 

Trying model with 50 estimator....
Model accuracy  on test set :81.97 

Trying model with 60 estimator....
Model accuracy  on test set :81.97 

Trying model with 70 estimator....
Model accuracy  on test set :81.97 

Trying model with 80 estimator....
Model accuracy  on test set :81.97 

Trying model with 90 estimator....
Model accuracy  on test set :78.69 



In [30]:
# save a model and load it 
import pickle

pickle.dump(clf,open("random_forst_model_1.pkl","wb"))

In [31]:
loaded_model=pickle.load(open("random_forst_model_1.pkl","rb"))
loaded_model.score(xtest,ytest)

0.7868852459016393

# 1.Get the data to be ready to be used

1 split the data x and y

2 fill the empty or partial data 

3 convert non zero to 


In [34]:
heart_dieseas.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [35]:
x =heart_dieseas.drop("target",axis=1)
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [36]:
y= heart_dieseas["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [8]:
#split the data

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=0.2)

In [9]:
xtrain.shape, xtest.shape,ytrain.shape,ytest.shape

((800, 4), (200, 4), (800,), (200,))

### make sure all the data is numerical

In [10]:
car_sales=pd.read_csv("data/car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [11]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [12]:
# split the data 
x=car_sales.drop("Price",axis=1)
y=car_sales["Price"]


In [13]:
xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=0.2)

In [14]:
#build the model

from sklearn.ensemble import RandomForestRegressor

model =RandomForestRegressor()
model.fit(xtrain,ytrain)
model.score(xtest,ytest)

ValueError: could not convert string to float: 'Toyota'

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

catagorical_feuture=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                               one_hot,
                               catagorical_feuture)],
                             remainder="passthrough")
transfromed_x=transformer.fit_transform(x)
transfromed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [16]:
pd.DataFrame(transfromed_x)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [17]:
dummies = pd.get_dummies(car_sales[["Make","Colour","Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [19]:
#let refit the model 
np.random.seed(42)
xtrain,xtest,ytrain,ytest=train_test_split(transfromed_x,y,test_size=0.2)
model.fit(xtrain,ytrain);

In [20]:
model.score(xtest,ytest)

0.3235867221569877

### missing data handling 

1 fill the data(imputation)

2 remove the data

In [35]:
car_miising_data = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_miising_data.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [36]:
x=car_miising_data.drop("Price",axis=1)
y=car_miising_data["Price"]

In [37]:
#try and convert it to number 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

catagorical_feuture=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                               one_hot,
                               catagorical_feuture)],
                             remainder="passthrough")
transfromed_x=transformer.fit_transform(x)
transfromed_x

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

#### fill missing data with pandas

In [39]:
car_miising_data["Make"].fillna("missing",inplace=True)
car_miising_data["Colour"].fillna("missing",inplace=True)
car_miising_data["Odometer (KM)"].fillna(car_miising_data["Odometer (KM)"].mean(),inplace=True)
car_miising_data["Doors"].fillna(4,inplace=True)

In [29]:
car_miising_data

Make   Colour       Odometer  Doors    Price
0   Toyota    White  150043.000000    4.0   $4,000
1    Honda      Red   87899.000000    4.0   $5,000
2   Toyota     Blue   92302.666667    3.0   $7,000
3      BMW    Black   11179.000000    5.0  $22,000
4   Nissan    White  213095.000000    4.0   $3,500
5   Toyota    Green   92302.666667    4.0   $4,500
6    Honda  missing   92302.666667    4.0   $7,500
7    Honda     Blue   92302.666667    4.0      NaN
8   Toyota    White   60000.000000    4.0      NaN
9  missing    White   31600.000000    4.0   $9,700

In [43]:
car_miising_data.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [41]:
car_miising_data.dropna(inplace=True)

In [42]:
car_miising_data

Make Colour  Odometer (KM)  Doors    Price
0      Honda  White        35431.0    4.0  15323.0
1        BMW   Blue       192714.0    5.0  19943.0
2      Honda  White        84714.0    4.0  28343.0
3     Toyota  White       154365.0    4.0  13434.0
4     Nissan   Blue       181577.0    3.0  14043.0
..       ...    ...            ...    ...      ...
995   Toyota  Black        35820.0    4.0  32042.0
996  missing  White       155144.0    3.0   5716.0
997   Nissan   Blue        66604.0    4.0  31570.0
998    Honda  White       215883.0    4.0   4001.0
999   Toyota   Blue       248360.0    4.0  12732.0

[950 rows x 5 columns]

In [44]:
x= car_miising_data.drop("Price",axis=1)
y = car_miising_data["Price"]

In [46]:
#try and convert it to number 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

catagorical_feuture=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                               one_hot,
                               catagorical_feuture)],
                             remainder="passthrough")
transfromed_x=transformer.fit_transform(car_miising_data)
transfromed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

### 2 fill the missing data using sci kit learn 

In [4]:
car_missing_data =pd.read_csv("data/car-sales-extended-missing-data.csv")
car_missing_data

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [5]:
car_missing_data.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [6]:
#drop the row with no label
car_missing_data.dropna(subset=["Price"],inplace=True)

In [7]:
car_missing_data.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [8]:
x=car_missing_data.drop("Price",axis=1)

In [9]:
y=car_missing_data["Price"]

In [10]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

cat_imputer =SimpleImputer(strategy="constant",fill_value="missing")
door_imputer=SimpleImputer(strategy="constant",fill_value=4)
num_imputer=SimpleImputer(strategy="mean")

cat_feature = ["Make","Colour"]
door_feature =["Doors"]
num_feature=["Odometer (KM)"]

imputer=ColumnTransformer([
    ("cat_imputer",cat_imputer,cat_feature),
    ("door_imputer",door_imputer,door_feature),
    ("num_imputer",num_imputer,num_feature)
])

filled_x=imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [11]:
car_sales_filled=pd.DataFrame(filled_x,
                              columns=["Make","Colour","Doors","Odometeer (KM)"])
car_sales_filled

Make Colour Doors Odometeer (KM)
0      Honda  White   4.0        35431.0
1        BMW   Blue   5.0       192714.0
2      Honda  White   4.0        84714.0
3     Toyota  White   4.0       154365.0
4     Nissan   Blue   3.0       181577.0
..       ...    ...   ...            ...
945   Toyota  Black   4.0        35820.0
946  missing  White   3.0       155144.0
947   Nissan   Blue   4.0        66604.0
948    Honda  White   4.0       215883.0
949   Toyota   Blue   4.0       248360.0

[950 rows x 4 columns]

In [12]:
car_sales_filled.isna().sum()

Make              0
Colour            0
Doors             0
Odometeer (KM)    0
dtype: int64

In [13]:
#try and convert it to number 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

catagorical_feuture=["Make","Colour","Doors"]
one_hot=OneHotEncoder()
transformer=ColumnTransformer([("one_hot",
                               one_hot,
                               catagorical_feuture)],
                             remainder="passthrough")
transfromed_x=transformer.fit_transform(car_sales_filled)
transfromed_x

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [14]:
#fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(transfromed_x,y,test_size=0.2)

model=RandomForestRegressor()
model.fit(xtrain,ytrain)
model.score(xtrain,ytrain)

0.8845872827949007

In [15]:
model.score(xtest,ytest)

0.21990196728583944

## 2 choosing the right estimator 

estmator is same as algorithm

* classificatiom -predicting one or other 
* regressor - predicting a number

### picking a model for regression problem

In [16]:
from sklearn.datasets import load_boston
boston = load_boston()
boston;

C:\Users\yuvar\OneDrive\Desktop\ML\ML1\env\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California 

In [18]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [19]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [20]:
raw_df

0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

## choosing a classification model

In [3]:
heart_diseas=pd.read_csv("data/heart-disease.csv")
heart_diseas.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [7]:
#Linear SVC
from sklearn.svm import LinearSVC


np.random.seed(42)

x= heart_diseas.drop("target",axis=1)
y=heart_diseas["target"]

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)


clf=LinearSVC(max_iter=1000)
clf.fit(xtrain,ytrain)

clf.score(xtest,ytest)


C:\Users\yuvar\OneDrive\Desktop\ML\ML1\env\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.8688524590163934

In [8]:
len(heart_diseas)

303

In [9]:
clf.score(xtrain,ytrain)

0.7933884297520661

In [14]:
#randomForestClassifier
from sklearn.ensemble import RandomForestClassifier


np.random.seed(42)

x= heart_diseas.drop("target",axis=1)
y=heart_diseas["target"]

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)


clf=RandomForestClassifier()
clf.fit(xtrain,ytrain)

clf.score(xtest,ytest)


0.8524590163934426

In [15]:
clf.score(xtrain,ytrain)

1.0

### fit the data to the model 

In [16]:
#randomForestClassifier
from sklearn.ensemble import RandomForestClassifier


np.random.seed(42)

#collect the data 
x= heart_diseas.drop("target",axis=1)
y=heart_diseas["target"]

#split the data 
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

#create the model instance 
clf=RandomForestClassifier()

#fit the data to the model
clf.fit(xtrain,ytrain)

#check the score of the choosen model
clf.score(xtest,ytest)


0.8524590163934426

In [17]:
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [18]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

### making prediction with our model

## use a trained model to make the predictio 

2 ways to make the prediction

1.predict()

2.predict_proba()

In [22]:
clf.predict(np.array([1,7,8,3,4]))

C:\Users\yuvar\OneDrive\Desktop\ML\ML1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 7. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [23]:
clf.predict(xtest)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [24]:
np.array(ytest)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [25]:
#Compare predction to the truth label

y_pred=clf.predict(xtest)
np.mean(y_pred==ytest)

0.8524590163934426

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,y_pred)

0.8524590163934426

### make prediction woth predict_proba()

In [27]:
clf.predict_proba(xtest[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [28]:
clf.predict(xtest[:5])

array([0, 1, 1, 0, 1], dtype=int64)

AUC /ROC